
~ 137 участников

	LitvinovaAA@rnbc.ru; 
		параметр	значение
		ФИО:	Литвинова Анна Александровна
		Подразделение:	Региональная сеть
		  Керченская
		    Операционный офис №270 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	LitvinovaAA@rncb.ru
		Телефон:	45347, +7 978 089-55-63
		День рождения:	23.02.1994
		Логин:	crimea\LitvinovaAA
		Адрес:	г. Керчь, ул. Ленина 17

	Абрамский Игорь Олегович; 
		параметр	значение
		ФИО:	Абрамский Игорь Олегович
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №3 РНКБ Банк (ПАО)
		      Отдел развития розничного бизнеса
		        Сектор прямых продаж
		Должность:	Главный специалист
		E-mail:	AbramskiyIO@rncb.ru
		Телефон:	45182, +79787304854
		День рождения:	14.10.1988
		Логин:	crimea\AbramskiyIO
		Адрес:	г. Севастополь, ул. Руднева 39в

	Абубекирова Лиля Ремзиевна; 

		параметр	значение
		ФИО:	Абубекирова Лиля Ремзиевна
		Подразделение:	Региональная сеть
		  Евпаторийская
		    Операционный офис №210 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Ведущий специалист
		E-mail:	AbubekirovaLR@rncb.ru
		Телефон:	48638, +79780327501
		День рождения:	16.07.1991
		Логин:	crimea\AbubekirovaLR
		Адрес:	г. Евпатория, ул. Матвеева 16а

	Аверин Олег Владимирович; 
		параметр	значение
		ФИО:	Аверин Олег Владимирович
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №189 РНКБ Банк (ПАО)
		Должность:	Директор
		E-mail:	AverinOV@rncb.ru
		Телефон:	47910, +79787294899
		День рождения:	29.07.1988
		Логин:	crimea\AverinOV
		Адрес:	пгт Аграрное, ул. Спортивная 10

	Аканов Максим Вадимович; 
		параметр	значение
		ФИО:	Аканов Максим Вадимович
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №3 РНКБ Банк (ПАО)
		      Отдел развития розничного бизнеса
		        Сектор прямых продаж
		Должность:	Главный специалист
		E-mail:	AkanovMV@rncb.ru
		Телефон:	45189, +79787836926
		День рождения:	15.09.1989
		Логин:	crimea\AkanovMV
		Адрес:	г. Севастополь, ул. Руднева 39в

	Алексанян Седа Ервандовна; 
		параметр	значение
		ФИО:	Алексанян Седа Ервандовна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №176 РНКБ Банк (ПАО)
		      Сектор координации розничного бизнеса
		Должность:	Региональный менеджер по продажам
		E-mail:	AleksanyanCE@rncb.ru
		Телефон:	46108, +7 978 703 55 57
		День рождения:	07.05.1978
		Логин:	crimea\AleksanyanCE
		Адрес:	г. Симферополь, ул. Маршала Василевского 2

	Алиева Елена Николаевна; 
		параметр	значение
		ФИО:	Алиева Елена Николаевна
		Подразделение:	Региональная сеть
		  Джанкойская
		    Операционный офис №100 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	AlievaEN@rncb.ru
		Телефон:	46308, 9788456617
		День рождения:	11.06.1990
		Логин:	crimea\AlievaEN
		Адрес:	г. Джанкой, ул. Крымская 55/2

	Алиева Эльмаз Рефатовна; 
		параметр	значение
		ФИО:	Алиева Эльмаз Рефатовна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №233 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	AlievaER@rncb.ru
		Телефон:	47781
		День рождения:	27.06.1989
		Логин:	crimea\AlievaER
		Адрес:	г. Симферополь, ул. Киевская 55а

	Андрюшкин Артур Арменович; 

		параметр	значение
		ФИО:	Андрюшкин Артур Арменович
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №288 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Главный специалист
		E-mail:	AndryushkinAA@rncb.ru
		Телефон:	45557, +79787428927
		День рождения:	27.01.1987
		Логин:	crimea\AndryushkinAA
		Адрес:	г. Симферополь, ул. Севастопольская 30/7

	Антоненко Ада Петровна; 
		параметр	значение
		ФИО:	Антоненко Ада Петровна
		Подразделение:	Региональная сеть
		  Красноперекопская
		    Операционный офис №163 РНКБ Банк (ПАО)
		Должность:	Заместитель директора по розничному бизнесу
		E-mail:	AntonenkoAP@rncb.ru
		Телефон:	46290, +7 978 875-33-01
		День рождения:	17.05.1965
		Логин:	crimea\AntonenkoAP
		Адрес:	г. Красноперекопск, ул. Менделеева 26а

	Апасов Андрей Андреевич; 
		параметр	значение
		ФИО:	Апасов Андрей Андреевич
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №274 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	ApasovAA@rncb.ru
		Телефон:	45386, +7 978 861 98 40
		День рождения:	27.01.1993
		Логин:	crimea\ApasovAA
		Адрес:	г. Симферополь, б-р Ленина 15

	Бабюк Надежда Борисовна; 
		параметр	значение
		ФИО:	Бабюк Надежда Борисовна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №176 РНКБ Банк (ПАО)
		      Отдел развития розничного бизнеса
		        Сектор прямых продаж
		Должность:	Главный специалист
		E-mail:	BabukNB@rncb.ru
		Телефон:	48686, +7 978-842-70-42
		День рождения:	13.12.1987
		Логин:	crimea\BabukNB
		Адрес:	г. Симферополь, пр-т. Победы 26

	Банщикова Анна Александровна; 
		параметр	значение
		ФИО:	Банщикова Анна Александровна
		Подразделение:	Региональная сеть
		  Феодосийская
		    Операционный офис №103 РНКБ Банк (ПАО)
		      Сектор кассовых операций
		Должность:	Кассир-операционист
		E-mail:	BanschikovaAA@rncb.ru
		Телефон:	48788, +79787005936
		День рождения:	14.09.1991
		Логин:	crimea\BanschikovaAA
		Адрес:	г. Судак, ул. Ленина 40

	Баранов Александр Викторович; 
		параметр	значение
		ФИО:	Баранов Александр Викторович
		Подразделение:	Департаменты
		  Управление по работе с персоналом
		    Отдел обучения
		Должность:	Главный специалист
		E-mail:	BaranovAV@rncb.ru
		Телефон:	46603, +79788382012
		День рождения:	01.06.1984
		Логин:	crimea\BaranovAV
		Адрес:	г. Симферополь, ул. Киевская 55а

	Бережная Анастасия Витальевна; 
		параметр	значение
		ФИО:	Бережная Анастасия Витальевна
		Подразделение:	Региональная сеть
		  Керченская
		    Операционный офис №154 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Главный специалист
		E-mail:	BerezhnayaAV@rncb.ru
		Телефон:	48302, +79787975830
		День рождения:	15.12.1982
		Логин:	crimea\BerezhnayaAV
		Адрес:	г. Керчь, ул. Ленина 44

	Боднар Елена Григорьевна; *
		параметр	значение
		ФИО:	Боднар Елена Григорьевна
		Подразделение:	Департаменты
		  Дирекция обслуживания юридических лиц
		    Отдел организации обслуживания
		Должность:	Региональный директор
		E-mail:	BodnarEG@rncb.ru
		Телефон:	47713, +7 978-729-99-39
		День рождения:	16.12.1973
		Логин:	crimea\BodnarEG
		Адрес:	г. Симферополь, ул. Героев Аджимушкая 1 этаж 3

	Боженова Елена Вячеславовна; 
		параметр	значение
		ФИО:	Боженова Елена Вячеславовна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №267 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Главный специалист
		E-mail:	BozhenovaEV@rncb.ru
		Телефон:	46822
		День рождения:	29.01.1984
		Логин:	crimea\BozhenovaEV
		Адрес:	г. Симферополь, ул. Героев Аджимушкая 1 этаж 3

	Большенко Татьяна Викторовна; 
		параметр	значение
		ФИО:	Большенко Татьяна Викторовна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №158 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Начальник сектора
		E-mail:	BolshenkoTV@rncb.ru
		Телефон:	48403, +7 978-783-70-25
		День рождения:	04.03.1983
		Логин:	crimea\BolshenkoTV
		Адрес:	г. Севастополь, пр-т. Генерала Острякова 158А

	Бондарева Екатерина Аркадьевна; 
		параметр	значение
		ФИО:	Бондарева Екатерина Аркадьевна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №3 РНКБ Банк (ПАО)
		      Отдел развития корпоративного бизнеса
		Должность:	Ведущий специалист
		E-mail:	BondarevaEA@rncb.ru
		Телефон:	47069, +79787669424
		День рождения:	02.06.1986
		Логин:	crimea\BondarevaEA
		Адрес:	г. Севастополь, ул. Руднева 39в

	Бондарчук Денис Петрович; 
		параметр	значение
		ФИО:	Бондарчук Денис Петрович
		Подразделение:	Региональная сеть
		  Керченская
		    Операционный офис №154 РНКБ Банк (ПАО)
		      Сектор координации розничного бизнеса
		Должность:	Региональный менеджер по продажам
		E-mail:	BondarchukDP@rncb.ru
		Телефон:	45204, +79787795864
		День рождения:	24.03.1986
		Логин:	crimea\BondarchukDP
		Адрес:	г. Керчь, ул. Ленина 44

	Бондарчук Светлана Алексеевна; 
		параметр	значение
		ФИО:	Бондарчук Светлана Алексеевна
		Подразделение:	Региональная сеть
		  Керченская
		    Операционный офис №72 РНКБ Банк (ПАО)
		Должность:	Директор
		E-mail:	BondarchukSA@rncb.ru
		Телефон:	48987, +7 978 779-58-63
		День рождения:	01.03.1985
		Логин:	crimea\BondarchukSA
		Адрес:	г. Керчь, ул. Горького 21

	Бочарова Надежда Владимировна; 
		параметр	значение
		ФИО:	Бочарова Надежда Владимировна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №191 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Ведущий специалист
		E-mail:	BocharovaNV@rncb.ru
		Телефон:	48378, +79787586897
		День рождения:	12.11.1987
		Логин:	crimea\BocharovaNV
		Адрес:	г. Симферополь, ул. Гагарина 34

	Бридель Виктория Александровна; 
		параметр	значение
		ФИО:	Бридель Виктория Александровна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №76 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Главный специалист
		E-mail:	BridelVA@rncb.ru
		Телефон:	45573, +7 978 764 45 72
		День рождения:	06.08.1990
		Логин:	crimea\BridelVA
		Адрес:	пгт Гвардейское, ул. Ленина 1а

	Вишневая Екатерина Владимировна; 
		параметр	значение
		ФИО:	Вишневая Екатерина Владимировна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №48 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Начальник сектора
		E-mail:	VishnevayaEV@rncb.ru
		Телефон:	47098, +7(978)7531421
		День рождения:	06.12.1989
		Логин:	crimea\VishnevayaEV
		Адрес:	г. Симферополь, ул. Набережная 32

	Волкова Наталья Аркадьевна; 
		параметр	значение
		ФИО:	Волкова Наталья Аркадьевна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №142 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Ведущий специалист
		E-mail:	VolkovaNA@rncb.ru
		Телефон:	47950, (+79788004951)
		День рождения:	13.12.1968
		Логин:	crimea\VolkovaNA
		Адрес:	г. Севастополь, ул. Генерала Жидилова 10

	Гавриленко Вадим Викторович; 
		параметр	значение
		ФИО:	Гавриленко Вадим Викторович
		Подразделение:	Департаменты
		  Управление по работе с персоналом
		    Отдел компенсаций и льгот
		Должность:	Специалист
		E-mail:	GavrilenkoVV@rncb.ru
		Телефон:	47964, +79781440263
		День рождения:	16.11.1988
		Логин:	crimea\GavrilenkoVV
		Адрес:	г. Симферополь, ул. Киевская 55а

	Герасименко Андрей Леонидович; 
		параметр	значение
		ФИО:	Герасименко Андрей Леонидович
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №274 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Главный специалист
		E-mail:	GerasimenkoAL@rncb.ru
		Телефон:	45385, +7 978 785 95 72
		День рождения:	05.04.1990
		Логин:	crimea\GerasimenkoAL
		Адрес:	г. Симферополь, б-р Ленина 15

	Герасимчик Екатерина Станиславовна; 
		параметр	значение
		ФИО:	Герасимчик Екатерина Станиславовна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №94 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Ведущий специалист
		E-mail:	GerasimchikES@rncb.ru
		Телефон:	46111, +7 978-720-66-75
		День рождения:	27.07.1982
		Логин:	crimea\GerasimchikES
		Адрес:	г. Севастополь, ул. Героев Севастополя 66

	Герман Надежда Сергеевна; 
		параметр	значение
		ФИО:	Герман Надежда Сергеевна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №264 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Ведущий специалист
		E-mail:	GermanNS@rncb.ru
		Телефон:	45541, +79787390306
		День рождения:	15.06.1989
		Логин:	crimea\GermanNS
		Адрес:	г. Севастополь, пр. Генерала Острякова 123г

	Гончарук Роман Владимирович; 
		параметр	значение
		ФИО:	Гончарук Роман Владимирович
		Подразделение:	Региональная сеть
		  Керченская
		    Операционный офис №270 РНКБ Банк (ПАО)
		Должность:	Директор
		E-mail:	GoncharukRV@rncb.ru
		Телефон:	45340, +7 978 727-27-99
		День рождения:	11.09.1983
		Логин:	crimea\GoncharukRV
		Адрес:	г. Керчь, ул. Ленина 17

	Гордюшина Татьяна Николаевна; 
		параметр	значение
		ФИО:	Гордюшина Татьяна Николаевна
		Подразделение:	Региональная сеть
		  Керченская
		    Операционный офис №91 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Главный специалист
		E-mail:	GordyushinaTN@rncb.ru
		Телефон:	47335, +7 978-800-33-78
		День рождения:	19.10.1986
		Логин:	crimea\GordyushinaTN
		Адрес:	г. Керчь, ул. Мирошника 3

	Горзуева Кристина Юрьевна; * 
		параметр	значение
		ФИО:	Горзуева Кристина Юрьевна
		Подразделение:	Региональная сеть
		  Джанкойская
		    Операционный офис №100 РНКБ Банк (ПАО)
		Должность:	Заместитель директора по розничному бизнесу
		E-mail:	GorzuevaKY@rncb.ru
		Телефон:	46306, +79787564655
		День рождения:	02.07.1983
		Логин:	crimea\GorzuevaKY
		Адрес:	г. Джанкой, ул. Ленина 21

	Горшкова Алёна Викторовна; 
		параметр	значение
		ФИО:	Горшкова Алёна Викторовна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №158 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Ведущий специалист
		E-mail:	GorshkovaAV@rncb.ru
		Телефон:	47980, +79788527729
		День рождения:	29.03.1985
		Логин:	crimea\GorshkovaAV
		Адрес:	г. Севастополь, пр-т. Генерала Острякова 158А

	Грекова Евгения Валерьевна; 
		параметр	значение
		ФИО:	Грекова Евгения Валерьевна
		Подразделение:	Региональная сеть
		  Евпаторийская
		    Операционный офис №88 РНКБ Банк (ПАО)
		      Сектор координации розничного бизнеса
		Должность:	Региональный менеджер по продажам
		E-mail:	GrekovaEV@rncb.ru
		Телефон:	48724, +7 978-855-86-89
		День рождения:	24.01.1982
		Логин:	crimea\GrekovaEV
		Адрес:	г. Евпатория, пр-т. Победы 4А

	Дембицкая Екатерина Александровна; *
		параметр	значение
		ФИО:	Дембицкая Екатерина Александровна
		Подразделение:	Департаменты
		  Управление рисков, мониторинга и проблемной задолженности
		    Отдел портфельных рисков
		Должность:	Главный специалист
		E-mail:	DembitskayaEA@rncb.ru
		Телефон:	46853, +79788988377
		День рождения:	20.02.1974
		Логин:	crimea\DembitskayaEA
		Адрес:	г. Симферополь, ул. Тренева 21

	Денисов Алексей Николаевич; 
		параметр	значение
		ФИО:	Денисов Алексей Николаевич
		Подразделение:	Региональная сеть
		  Евпаторийская
		    Операционный офис №97 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	DenisovAN@rncb.ru
		Телефон:	47371, +79780544833
		День рождения:	06.07.1990
		Логин:	crimea\DenisovAN
		Адрес:	г. Черноморское, ул. Революции 7

	Джелялов Эмир Русланович; 
		параметр	значение
		ФИО:	Джелялов Эмир Русланович
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №231 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Ведущий специалист
		E-mail:	DjelylovER@rncb.ru
		Телефон:	46303, +7 978 857-30-90
		День рождения:	18.08.1987
		Логин:	crimea\DjelylovER
		Адрес:	г. Симферополь, ул. Севастопольская 22/2

	Дубенцов Артур Алексеевич; * 
		параметр	значение
		ФИО:	Дубенцов Артур Алексеевич
		Подразделение:	Департаменты
		  Управление комплаенс-контроля
		    Отдел финансового мониторинга
		      Группа анализа операций клиентов
		Должность:	Главный специалист
		E-mail:	DubentsovAA@rncb.ru
		Телефон:	46729
		День рождения:	16.12.1983
		Логин:	crimea\DubentsovAA
		Адрес:	г. Симферополь, ул. Киевская 55а

	Дубовицкая Елена Сергеевна; 
		параметр	значение
		ФИО:	Дубовицкая Елена Сергеевна
		Подразделение:	Региональная сеть
		  Джанкойская
		    Операционный офис №100 РНКБ Банк (ПАО)
		      Сектор координации розничного бизнеса
		Должность:	Региональный менеджер по продажам
		E-mail:	DubovitskayaES@rncb.ru
		Телефон:	46079, +7 978 846-88-95
		День рождения:	22.07.1983
		Логин:	crimea\DubovitskayaES
		Адрес:	г. Джанкой, ул. Ленина 21

	Ефименко Людмила Викторовна; 
		параметр	значение
		ФИО:	Ефименко Людмила Викторовна
		Подразделение:	Региональная сеть
		  Керченская
		    Операционный офис №154 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Главный специалист
		E-mail:	EfimenkoLW@rncb.ru
		Телефон:	48392, +7 978 820 99 08
		День рождения:	29.01.1983
		Логин:	crimea\EfimenkoLW
		Адрес:	г. Керчь, ул. Ленина 44

	Жирнова Елена Александровна; *
		параметр	значение
		ФИО:	Жирнова Елена Александровна
		Подразделение:	Департаменты
		  Юридический департамент
		    Отдел обеспечения кредитных операций и сделок
		Должность:	Главный юрисконсульт
		E-mail:	ZhirnovaEA@rncb.ru
		Телефон:	47630, 8-913-981-35-31
		День рождения:	11.02.1990
		Логин:	crimea\ZhirnovaEA
		Адрес:	г. Симферополь, ул. Набережная 32

	Журавлева Елена Валериевна; 
		параметр	значение
		ФИО:	Журавлева Елена Валериевна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №231 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Ведущий специалист
		E-mail:	JuravlevaEV@rncb.ru
		Телефон:	46587, +79787531412
		День рождения:	02.01.1988
		Логин:	crimea\JuravlevaEV
		Адрес:	г. Симферополь, ул. Севастопольская 22/2

	Землянская Елизавета Павловна; 
		параметр	значение
		ФИО:	Землянская Елизавета Павловна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №94 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Главный специалист
		E-mail:	ZemlyanskayaEP@rncb.ru
		Телефон:	48322, +7(978)731-19-84
		День рождения:	04.06.1991
		Логин:	crimea\ZemlyanskayaEP
		Адрес:	г. Севастополь, ул. Героев Севастополя 66

	Зорук Наталья Александровна; 
		параметр	значение
		ФИО:	Зорук Наталья Александровна
		Подразделение:	Региональная сеть
		  Феодосийская
		    Операционный офис №10 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Главный специалист
		E-mail:	ZorukNA@rncb.ru
		Телефон:	48369, +79788083684
		День рождения:	08.08.1984
		Логин:	crimea\ZorukNA
		Адрес:	г. Феодосия, ул. Советская 13

	Иваницкая Лилия Андреевна; 
		параметр	значение
		ФИО:	Иваницкая Лилия Андреевна
		Подразделение:	Региональная сеть
		  Феодосийская
		    Операционный офис №103 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	IvanitskayaLA@rncb.ru
		Телефон:	47165, +7 978 851 02 46
		День рождения:	25.11.1995
		Логин:	crimea\IvanitskayaLA
		Адрес:	г. Судак, ул. Ленина 40

	Ивашин Дмитрий Васильевич; 
		параметр	значение
		ФИО:	Ивашин Дмитрий Васильевич
		Подразделение:	Региональная сеть
		  Евпаторийская
		    Операционный офис №210 РНКБ Банк (ПАО)
		Должность:	Директор
		E-mail:	IvashinDV@rncb.ru
		Телефон:	48637, +79787036960
		День рождения:	28.08.1985
		Логин:	crimea\IvashinDV
		Адрес:	г. Евпатория, ул. Матвеева 16а

	Ивашина Елена Дмитриевна; 
		параметр	значение
		ФИО:	Ивашина Елена Дмитриевна
		Подразделение:	Региональная сеть
		  Евпаторийская
		    Операционный офис №88 РНКБ Банк (ПАО)
		Должность:	Заместитель директора по розничному бизнесу
		E-mail:	IvashinaED@rncb.ru
		Телефон:	48735, +7 978 732-15-45
		День рождения:	21.04.1966
		Логин:	crimea\IvashinaED
		Адрес:	г. Евпатория, пр-т. Победы 4А

	Изместьев Кирилл Евгеньевич; *
		параметр	значение
		ФИО:	Изместьев Кирилл Евгеньевич
		Подразделение:	Департаменты
		  Дирекция розничных продаж в корпоративном канале
		    Отдел продаж и обслуживания эквайринга
		      Группа развития эквайринга
		Должность:	Директор
		E-mail:	IzmestevKE@rncb.ru
		Телефон:	47676, +7 978 729 96 69
		День рождения:	14.06.1983
		Логин:	crimea\IzmestevKE
		Адрес:	г. Симферополь, ул. Героев Аджимушкая 1 этаж 2

	Ильясова Ленара Эдемовна; 
		параметр	значение
		ФИО:	Ильясова Ленара Эдемовна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №157 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	IlyasovaLE1@rncb.ru
		Телефон:	48632, +79788228361
		День рождения:	10.04.1993
		Логин:	crimea\IlyasovaLE1
		Адрес:	г. Симферополь, ул. Киевская/Фрунзе6 корп. 1

	Калайда Юлия Владимировна; 
		параметр	значение
		ФИО:	Калайда Юлия Владимировна
		Подразделение:	Региональная сеть
		  Красноперекопская
		    Операционный офис №163 РНКБ Банк (ПАО)
		      Сектор координации розничного бизнеса
		Должность:	Региональный менеджер по продажам
		E-mail:	KalaydaUV@rncb.ru
		Телефон:	47159, +7 978 823-27-76
		День рождения:	27.12.1980
		Логин:	crimea\KalaydaUV
		Адрес:	г. Красноперекопск, ул. Менделеева 26а

	Карелина Виктория Сергеевна; 
		параметр	значение
		ФИО:	Карелина Виктория Сергеевна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №64 РНКБ Банк (ПАО)
		Должность:	Директор
		E-mail:	KarelinaVS@rncb.ru
		Телефон:	46616, +7 978 764-91-88
		День рождения:	15.10.1984
		Логин:	crimea\KarelinaVS
		Адрес:	пгт Николаевка, ул. Набережная 1

	Каунова Евгения Николаевна; 
		параметр	значение
		ФИО:	Каунова Евгения Николаевна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №235 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Ведущий специалист
		E-mail:	KaunovaEN@rncb.ru
		Телефон:	46718, +7 978 788-45-20
		День рождения:	18.02.1992
		Логин:	crimea\KaunovaEN
		Адрес:	г. Севастополь, пр-т. Генерала Острякова 80

	Ким Надежда Инокентьевна; 
		параметр	значение
		ФИО:	Ким Надежда Инокентьевна
		Подразделение:	Департаменты
		  Управление по работе с персоналом
		    Отдел обучения
		Должность:	Ведущий специалист
		E-mail:	KimNI@rncb.ru
		Телефон:	45178
		День рождения:	02.05.1987
		Логин:	crimea\KimNI
		Адрес:	г. Симферополь, ул. Киевская 55а

	Клименко Владимир Дмитриевич; 
		параметр	значение
		ФИО:	Клименко Владимир Дмитриевич
		Подразделение:	Региональная сеть
		  Евпаторийская
		    Операционный офис №109 РНКБ Банк (ПАО)
		Должность:	Директор
		E-mail:	KlimenkoVD@rncb.ru
		Телефон:	47220, +7-97-88-55-12-11 +79-78-72-72-533 +065-58-20588 +380990531551
		День рождения:	22.02.1952
		Логин:	crimea\KlimenkoVD
		Адрес:	г. Черноморское, ул. Кирова 43

	Коготова Виктория Владимировна; 
		параметр	значение
		ФИО:	Коготова Виктория Владимировна
		Подразделение:	Региональная сеть
		  Феодосийская
		    Операционный офис №153 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	KogotovaVV@rncb.ru
		Телефон:	47962, 978 850-87-44
		День рождения:	16.02.1989
		Логин:	crimea\KogotovaVV
		Адрес:	г. Кировское, ул. Кирова 15

	Козленко Константин Геннадьевич; 
		параметр	значение
		ФИО:	Козленко Константин Геннадьевич
		Подразделение:	Региональная сеть
		  Евпаторийская
		    Операционный офис №88 РНКБ Банк (ПАО)
		      Сектор координации розничного бизнеса
		Должность:	Региональный менеджер по продажам
		E-mail:	KozlenkoKG@rncb.ru
		Телефон:	48730, +7 978 008 54 74
		День рождения:	29.05.1979
		Логин:	crimea\KozlenkoKG
		Адрес:	г. Евпатория, пр-т. Победы 4А

	Колобков Виктор Александрович; 
		параметр	значение
		ФИО:	Колобков Виктор Александрович
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №241 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Главный специалист
		E-mail:	KolobkovVA@rncb.ru
		Телефон:	45290, +7 978 813-51-89
		День рождения:	17.01.1990
		Логин:	crimea\KolobkovVA
		Адрес:	г. Севастополь, пр. Героев Сталинграда 27

	Колобкова Ольга Игоревна; 
		параметр	значение
		ФИО:	Колобкова Ольга Игоревна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №158 РНКБ Банк (ПАО)
		      Сектор обслуживания юридических лиц
		Должность:	Ведущий специалист
		E-mail:	KolobkovaOI@rncb.ru
		Телефон:	48402, +7 978 813 5207
		День рождения:	03.03.1989
		Логин:	crimea\KolobkovaOI
		Адрес:	г. Севастополь, пр-т. Генерала Острякова 158А

	Кондрашов Сергей Константинович; 
		параметр	значение
		ФИО:	Кондрашов Сергей Константинович
		Подразделение:	Региональная сеть
		  Джанкойская
		    Операционный офис №105 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Администратор зала
		E-mail:	KondrashovSK@rncb.ru
		Телефон:	46355, 9787826264
		День рождения:	30.10.1992
		Логин:	crimea\KondrashovSK
		Адрес:	г. Нижнегорский, ул. Победы 87

	Коновалова Елена Александровна; 
		параметр	значение
		ФИО:	Коновалова Елена Александровна
		Подразделение:	Региональная сеть
		  Ялтинская
		    Операционный офис №217 РНКБ Банк (ПАО)
		      Сектор координации розничного бизнеса
		Должность:	Региональный менеджер по продажам
		E-mail:	KonovalovaEA@rncb.ru
		Телефон:	47877, +380985735555 +79787501737
		День рождения:	11.12.1979
		Логин:	crimea\KonovalovaEA
		Адрес:	г. Алушта, ул. Хромых 21а

	Костренкова Валерия Сергеевна; 
		параметр	значение
		ФИО:	Костренкова Валерия Сергеевна
		Подразделение:	Региональная сеть
		  Симферопольская
		    Операционный офис №285 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	KostrenkovaVS@rncb.ru
		Телефон:	46657, +79787037133
		День рождения:	08.01.1993
		Логин:	crimea\KostrenkovaVS
		Адрес:	г. Симферополь, ул. Кечкеметская 1

	Крайнов Юрий Юрьевич; 
		параметр	значение
		ФИО:	Крайнов Юрий Юрьевич
		Подразделение:	Департаменты
		  Управление информационных технологий
		    Отдел сопровождения устройств самообслуживания
		      Группа мониторинга устройств самообслуживания
		Должность:	Специалист
		E-mail:	KraynovYY@rncb.ru
		Телефон:	47507, +79787671150
		День рождения:	16.10.1991
		Логин:	crimea\KraynovYY
		Адрес:	г. Симферополь, ул. Севастопольская 62

	Красюк Ольга Валентиновна; 
		параметр	значение
		ФИО:	Красюк Ольга Валентиновна
		Подразделение:	Региональная сеть
		  Керченская
		    Операционный офис №183 РНКБ Банк (ПАО)
		      Сектор продаж и обслуживания
		Должность:	Специалист
		E-mail:	KrasyukOV@rncb.ru
		Телефон:	45447, +79788355482
		День рождения:	29.05.1985
		Логин:	crimea\KrasyukOV
		Адрес:	г. Керчь, ул. Войкова 28

	Ктиторчук Полина Юрьевна; 
		параметр	значение
		ФИО:	Ктиторчук Полина Юрьевна
		Подразделение:	Региональная сеть
		  Севастопольская
		    Операционный офис №3 РНКБ Банк (ПАО)
		      Сектор координации розничного бизнеса
		Должность:	Региональный менеджер по продажам
		E-mail:	KtitorukPY@rncb.ru
		Телефон:	46170, +79788148608
		День рождения:	24.09.1984
		Логин:	crimea\KtitorukPY
		Адрес:	г. Севастополь, ул. Руднева 39в

	Кузеванова Анна Игоревна; 
	Кузнецова Татьяна Александровна; *
	Куренкова Ксения Викторовна; 
	Куринной Александр Васильевич; 
	Кутищева Маргарита Геннадиевна; 
	Лещенко Кристина Вячеславовна; 

	Лисовая Фаина Сергеевна; **
		параметр	значение
		ФИО:	Лисовая Фаина Сергеевна
		Подразделение:	Департаменты
		  Управление розничных продуктов, аналитики и методологии
		Должность:	Начальник Управления
		E-mail:	LisovayaFS@rncb.ru
		Телефон:	47989, +7 978-753-81-96
		День рождения:	14.02.1980
		Логин:	crimea\LisovayaFS
		Адрес:	г. Симферополь, ул. Героев Аджимушкая 1 этаж 3

	Луговская Галина Витальевна; 
	Лукашенок Юлия Викторовна; 
	Ляшенко Юлия Викторовна; 
	Мамутова Мавиле Мурадовна
	Мартынюк Артем Александрович; *
	Маслак Екатерина Викторовна; 
	Мащенко Магдалена Викентьевна; 
	Метересова Татьяна Сергеевна; 
	Минаев Андрей Вячеславович; 
	Молдован Роман Сергеевич; 
	Мосиенко Оксана Александровна; 
	Мочалова Софья Сергеевна; 
	Набиев Александр Чингизович; 
	Недашковская Елена Анатольевна; 
	Неустроева Екатерина Сергеевна; 
	Новикова Наталья Викторовна; 
	Носенко Дарья Александровна; 
	Паер Екатерина Александровна; 
	Панюжева Наталья Викторовна; 
	Паршукова Екатерина Викторовна; 
	Подгорецкий Владислав Анатольевич; 
	Подрезенко Роман; 
	Покулев Михаил Юрьевич; 
	Помазан Игорь Валентинович; 
	Прокопов Кирилл Валерьевич; 
	Пронь Александра Павловна; 
	Прусаков Владислав Сергеевич; 
	Пучкова Марина Андреевна; 
	Разгонов Евгений Сергеевич; 
	Ревтов Кирилл Олегович; 
	Реутов Андрей Николаевич; 
	Романова Виктория Николаевна; 
	Рубцова Олеся Ивановна; 
	Рудиков Александр Васильевич; 
	Савицкая Ольга Олеговна; 
	Самотова Мария Игоревна; 
	Сафронова Татьяна Валерьевна; 
	Севдималиева Елена Геннадиевна; 
	Середницкий Расим Расимович; 
	Сигнеева Анна Сергеевна; 
	Скворцова Ольга Владимировна; 
	Сметанюк Александр Олегович; 
	Спевак Анна Вадимовна; 
	Степанова Валентина Васильевна; 
	Стоянов Леонид Александрович; 
	Суркова Дарья Владимировна; 
	Сычук Ирина Петровна; 
	Тарасенко Евгений Викторович; 
	Тарасова Марина Николаевна; 
	Терещенко Анна Александровна; 
	Трайнина Наталья Леонидовна; 
	Троицкая Елена Вячеславовна; 
	Узун Александра Викторовна; 
	Уманская Ирина Викторовна; 
	Фабриков Анатолий Викторович; 
	Хлопов Игорь Васильевич; 
	Холодняк Алексей Александрович; 
	Чемерис Сергей Юрьевич; 
	Чугунова Виолетта Андреевна; 
	Чумертова Анна Александровна; 
	Шаповалова Кристина Владимировна; 
	Шатилова Лидия Сергеевна; 
	Шевкиев Эмир Нуриевич; 
	Шумко Артем Павлович; 
	Юрченко Ольга Викторовна; 
	Ященко Сергей Анатольевич; 

	137 участников
------------------------------------------------------------------------------
~ daybook
------------------------------------------------------------------------------
* ПН [0/4]
	[X] Чему я научился сегодня? Что нового узнал?
	[ ] Кому и за что я благодарен сегодня?
	[ ] Что я хочу от завтрашнего дня?
	[ ] Мои спортивные достижения.
[ ] 
------------------------------------------------------------------------------
* ВТ [0/4]
	[ ] Чему я научился сегодня? Что нового узнал?
	[ ] Как можно было бы сделать этот день лучше?
	[ ] Что я хочу от затрашнего дня?
	[ ] Мои спортивные достижения.
[ ] 
------------------------------------------------------------------------------
* СР [0/4]
	[ ] Чему я научился сегодня? Что нового узнал?
	[ ] Что меня сегодня вдохновляло или мотивировало в работе?
	[ ] Что я хочу от затрашнего дня?
	[ ] Мои спортивные достижения.
[ ] 
------------------------------------------------------------------------------
* ЧТ [0/4]
	[ ] Чему я научился сегодня? Что нового узнал?
	[ ] Что полезного я сделал сегодня?
	[ ] Что я хочу от затрашнего дня?
	[ ] Мои спортивные достижения.
[ ] 
------------------------------------------------------------------------------
* ПТ [0/4]
	[ ] Чему я научился сегодня? Что нового узнал?
	[ ] За что я хвалю себя сегодня?
	[ ] Что я хочу от затрашнего дня?
	[ ] Мои спортивные достижения.
[ ] 
------------------------------------------------------------------------------
* СБ [0/4]
	[ ] Чему я научился сегодня? Что нового узнал?
	[ ] Что еще я бы мог сделать сегодня?
	[ ] Что я хочу от затрашнего дня?
	[ ] Мои спортивные достижения.
[ ] 
------------------------------------------------------------------------------
* ВС [0/8]
	[ ] Какие основные выводы я сделал для себя на этой неделе?
	[ ] Мое самое большое достижение за эту неделю?
	[ ] Что мне помогало достичь результатов на этой неделе?
	[ ] Что мешало мне достичь лучших результатов на этой неделе?
	[ ] Какие возможности есть в моем распоряжении?
	[ ] Что из того, что я откладываю, нужно сделать на следующей неделе?
	[ ] Мои цели на следующую неделю?
	[ ] Мои спортивные достижения за неделю.
[ ] 
------------------------------------------------------------------------------
* Для новых идей
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
------------------------------------------------------------------------------
* Я понял
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
------------------------------------------------------------------------------
* Я сделал
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
------------------------------------------------------------------------------
* Чем я горжусь
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
	[ ] 
------------------------------------------------------------------------------



